/**:
  ros__parameters:
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    arena_x_length: 6.0
    arena_y_length: 7.0
    obstacles:
      x: [-0.5, 0.8, 0.4, 0.5, 0.8]
      y: [-0.7, -0.8, 0.8, 0.0, 0.0]
      r: 0.038
